import z from "zod"
import path from "path"
import { Config } from "../config/config"
import { Instance } from "../project/instance"
import { NamedError } from "@opencode-ai/util/error"
import { ConfigMarkdown } from "../config/markdown"
import { Log } from "../util/log"
import { Global } from "@/global"
import { Filesystem } from "@/util/filesystem"
import { Flag } from "@/flag/flag"
import { Bus } from "@/bus"
import { TuiEvent } from "@/cli/cmd/tui/event"
import { Session } from "@/session"

export namespace Skill {
  const log = Log.create({ service: "skill" })

  const BUILTIN_SKILLS = [
    {
      name: "initskill",
      description: "Install default document/obsidian skills if missing",
      content: [
        "## Skill: initskill",
        "",
        "Bootstrap default skills using /skill-install, only installing missing ones.",
        "",
        "### Default skill sources",
        "- docx: https://github.com/ComposioHQ/awesome-claude-skills/tree/master/document-skills/docx",
        "- pdf: https://github.com/ComposioHQ/awesome-claude-skills/tree/master/document-skills/pdf",
        "- pptx: https://github.com/ComposioHQ/awesome-claude-skills/tree/master/document-skills/pptx",
        "- xlsx: https://github.com/ComposioHQ/awesome-claude-skills/tree/master/document-skills/xlsx",
        "- json-canvas: https://github.com/kepano/obsidian-skills/tree/main/skills/json-canvas",
        "- obsidian-bases: https://github.com/kepano/obsidian-skills/tree/main/skills/obsidian-bases",
        "- obsidian-markdown: https://github.com/kepano/obsidian-skills/tree/main/skills/obsidian-markdown",
        "",
        "### Steps",
        "1) Determine target scope/path. If the user specified scope/path, use it; otherwise default to global (the /skill-install default).",
        "2) Check which skills are already installed in that scope (use /skill-list with scope/path if available, or inspect the skill folders).",
        "3) For each missing skill, run /skill-install with the URL (optionally include --subpath matching the path after /tree/<ref>/).",
        "4) Summarize installed vs already present. If any install fails, surface the error and suggest retrying.",
        "",
        "### Expected skill names",
        "- docx, pdf, pptx, xlsx, json-canvas, obsidian-bases, obsidian-markdown",
        "",
        "### Rules",
        "- Do not reinstall existing skills unless the user asks.",
        "- Do not delete/overwrite existing skills unless the user explicitly requests --force.",
        "- If network access is blocked, ask the user to enable it or provide local files.",
      ].join("\n"),
    },
    {
      name: "cn-mirror-fallback",
      description:
        "Auto fallback to China mirrors when downloads/installations fail (temporary overrides only)",
      content: [
        "## Skill: cn-mirror-fallback",
        "",
        "Automatically recover from external download failures by retrying with a China mirror using temporary,",
        "per-command overrides only.",
        "",
        "### Trigger (use proactively)",
        "- Download/install errors: timeout, DNS failure, TLS reset, 403/429, ECONNRESET, ETIMEDOUT, ENOTFOUND",
        '- User reports: "外网下载不行", "下载失败", "连接不上", "卡在下载"',
        "",
        "### Goals",
        "- Identify the tool and the exact URL/registry being used",
        "- Retry with a domestic mirror or proxy without persisting config",
        "- Keep changes scoped to the single command/process",
        "",
        "### Workflow",
        "1) Identify the failing tool and resource type (registry, GitHub release, CDN asset, OS package, browser)",
        "2) Prefer a per-command flag or env var to override registry/mirror host",
        "3) Pick a mirror: user preference > repo config > a well-known CN mirror set",
        "4) Retry once with a temporary override (inline env or temp config file)",
        "5) Report which mirror was used and that it was temporary",
        "6) If it still fails, ask whether to persist config or use a proxy/VPN",
        "",
        "### Temporary override patterns (examples)",
        "- Generic: `ENV_VAR=value <command>` (do not write global rc files)",
        "- Registry-based tools: prefer `--registry <mirror>` or equivalent per-command option",
        "- Python/pip: pass `-i <mirror> --trusted-host <host>` on the command",
        "- Go: set `GOPROXY=<mirror>,direct` for the command",
        "- GitHub/CDN assets: swap host to a mirror/proxy or download manually then point the tool to local cache",
        "- Browser binaries (e.g., Playwright): override download host via tool env var if supported; otherwise",
        "  download from mirror and set the tool to use the local cache path",
        "",
        "### Rules",
        "- Do not persist config files unless the user explicitly agrees",
        "- Keep mirror choice flexible; do not hardcode a single provider",
        "- Prefer a single mirror retry before asking the user for next steps",
        "- If the tool supports a cache directory option, use a temp cache to avoid global changes",
      ].join("\n"),
    },
    {
      name: "doc-outline",
      description: "Generate a doc outline with sources + gaps (structured)",
      content: [
        "## Skill: doc-outline",
        "",
        "Create a high-quality outline for a document, and explicitly track sources and missing information.",
        "",
        "### Inputs",
        "- The user's goal, audience, doc type (PRD/TDD/runbook/etc), constraints",
        "- Optional: imported source materials (use `doc_import` first for .docx/.pptx/.xlsx/.pdf)",
        "",
        "### Doc taxonomy (use if doc_type unclear)",
        "- Requirements analysis: problem statement, users/use cases, functional + non-functional reqs, constraints, acceptance",
        "- Feasibility study: options, technical/operational/schedule feasibility, cost/ROI, risks, recommendation",
        "- Software design (SDD): architecture, components, data flow/DFD, interfaces, data model, interaction/sequence",
        "- Technical design (TDD): architecture, data model, APIs, failure modes, rollout",
        "- Test plan: objectives, strategy, cases, environments, entry/exit criteria",
        "- Runbook/postmortem/threat model/release notes as applicable",
        "",
        "### Output (required, YAML)",
        "```yml",
        "schema: doc.outline.v1",
        "title: \"\"",
        "doc_type: \"\"",
        "audience: \"\"",
        "sections:",
        "  - id: \"S1\"",
        "    heading: \"\"",
        "    intent: \"\"",
        "    required_inputs: []",
        "open_questions: []",
        "sources:",
        "  - kind: \"user|imported|repo\"",
        "    note: \"\"",
        "```",
        "",
        "### Checklist (answer each item)",
        "- [ ] Each section has a clear intent and required inputs",
        "- [ ] Unknowns are listed as open_questions (do not invent)",
        "- [ ] Sources are listed (where each major claim will come from)",
      ].join("\n"),
    },
    {
      name: "doc-detect",
      description: "Detect document intent/type and recommend a template",
      content: [
        "## Skill: doc-detect",
        "",
        "Classify the user's intent, infer the best document type, and recommend a template/outline.",
        "",
        "### Inputs",
        "- The user's request + context",
        "- Optional: imported source materials (use `doc_import` for .docx/.pptx/.xlsx/.pdf)",
        "- Optional: repo context / existing docs or templates",
        "",
        "### Output (required, YAML)",
        "```yml",
        "schema: doc.detect.v1",
        "doc_intent: \"\"",
        "doc_type: \"\"",
        "recommended_templates:",
        "  - template_id: \"\"",
        "    reason: \"\"",
        "required_sections: []",
        "missing_inputs: []",
        "sources:",
        "  - kind: \"user|imported|repo\"",
        "    note: \"\"",
        "confidence: 0.0",
        "```",
        "",
        "### Rules",
        "- If a file path is provided, import it and use its structure as evidence.",
        "- Prefer templates that already exist in the repo/tooling; otherwise propose a domain + doc_type template_id for auto inference.",
        "- If intent is ambiguous, list missing_inputs and ask targeted questions.",
        "- Do not invent facts; tie decisions to sources.",
      ].join("\n"),
    },
    {
      name: "doc-flow",
      description: "Doc workflow using only docx/pdf/pptx/xlsx skills",
      content: [
        "## Skill: doc-flow",
        "",
        "Orchestrate a document workflow using ONLY the docx/pdf/pptx/xlsx skills for file IO.",
        "",
        "### Inputs",
        "- The user's request + context",
        "- Optional: source files (.docx/.pdf/.pptx/.xlsx) and desired outputs",
        "- Optional: repo context / existing docs or templates",
        "",
        "### Output (required, YAML)",
        "```yml",
        "schema: doc.flow.v1",
        "domain: \"\"",
        "domain_confidence: 0.0",
        "doc_catalog:",
        "  - doc_type: \"\"",
        "    purpose: \"\"",
        "    template_md: \"\"",
        "    output_format: \"md|docx|pdf|pptx|xlsx\"",
        "    required: false",
        "recommended_docs: []",
        "missing_inputs: []",
        "sources:",
        "  - kind: \"user|imported|repo\"",
        "    note: \"\"",
        "next_action: \"ask_user_selection|proceed\"",
        "```",
        "",
        "### Rules",
        "- ONLY use skills named `docx` / `pdf` / `pptx` / `xlsx` for any file reading, writing, or conversion.",
        "- Do NOT call other doc skills or tools (e.g., doc-outline/doc-fill/doc-style/doc-review/doc-convert/doc_import/doc_template_render).",
        "- If a required file skill is missing, ask the user to run /skill-init or /skill-install.",
        "- If the user provides a file path with one of the four extensions, load the corresponding skill first and extract needed content.",
        "- Draft outlines and content directly in markdown/plain text; do not rely on other doc skills.",
        "- Ask for confirmation after outlining and before generating final outputs.",
        "- For exports, generate the target format via the matching skill; keep a markdown copy for review if helpful.",
      ].join("\n"),
    },
    {
      name: "doc-style",
      description: "Normalize doc metadata and styling before export",
      content: [
        "## Skill: doc-style",
        "",
        "Standardize document metadata, structure, and styling before export. Produce a clean, consistent Markdown output.",
        "",
        "### Inputs",
        "- Draft markdown text (from `doc-fill` or docx->md conversion)",
        "- User style preferences (fonts, sizes, spacing, toc depth)",
        "- Output target (markdown/docx/pdf)",
        "",
        "### Output (required, YAML)",
        "```yml",
        "schema: doc.style.v1",
        "metadata:",
        "  title: \"\"",
        "  author: \"\"",
        "  version: \"\"",
        "  date: \"\"",
        "  status: \"\"",
        "style_profile:",
        "  output: \"markdown|docx|pdf\"",
        "  font_body: \"\"",
        "  font_heading: \"\"",
        "  font_mono: \"\"",
        "  font_size_pt: 11",
        "  line_spacing: \"1.5\"",
        "  paragraph_spacing_before_pt: 0",
        "  paragraph_spacing_after_pt: 6",
        "  toc: true",
        "  toc_depth: 5",
        "  diagram_style: \"mermaid\"",
        "  first_line_indent_chars: 2",
        "export_hints:",
        "  reference_docx: \"\"",
        "  pandoc_args: []",
        "styled_markdown: |",
        "  ---",
        "  title: \"\"",
        "  author: \"\"",
        "  date: \"\"",
        "  ---",
        "  # ...",
        "```",
        "",
        "### Rules",
        "- If input is .doc/.docx, convert to .md first before applying style.",
        "- If style preferences are missing, ask targeted questions; if the user does not provide, apply defaults below and state them.",
        "- Normalize heading levels (H1 title, H2 sections, H3 subsections).",
        "- Ensure each heading is a standalone line; do not combine multiple sections in one heading.",
        "- Do not generate a manual TOC list when exporting to docx; rely on pandoc `--toc` instead.",
        "- For architecture/dataflow/sequence/state/ER diagrams, use Mermaid code blocks.",
        "- If output is docx/pdf and Mermaid blocks are present, call `doc_diagram_render` to replace them with images before export.",
        "- Apply first-line indent only to normal paragraphs (not headings, lists, blockquotes, tables, code blocks).",
        "- If no reference_docx is provided, warn that exact fonts/paragraph styles may not match in docx.",
        "- Keep code blocks monospace and do not alter code identifiers.",
        "",
        "### Defaults (when user does not specify)",
        "- font_body: SimSun (fallback: Microsoft YaHei)",
        "- font_heading: SimHei (bold)",
        "- font_mono: Consolas",
        "- font_size_pt: 11",
        "- line_spacing: 1.5",
        "- paragraph_spacing_before_pt: 0",
        "- paragraph_spacing_after_pt: 6",
        "- toc: true",
        "- toc_depth: 5",
        "- diagram_style: mermaid",
        "- first_line_indent_chars: 2",
      ].join("\n"),
    },
    {
      name: "doc-fill",
      description: "Fill a template into a complete doc (source-aware)",
      content: [
        "## Skill: doc-fill",
        "",
        "Fill a document template into a draft that is complete enough to review, without inventing facts.",
        "",
        "### Inputs",
        "- A template (prefer `doc_template_render` if starting fresh)",
        "- Source materials (user input and/or `doc_import` output)",
        "",
        "### Output (required, YAML)",
        "```yml",
        "schema: doc.fill.v1",
        "filled_markdown: |",
        "  # ...",
        "assumptions: []",
        "open_questions: []",
        "claims:",
        "  - claim: \"\"",
        "    source: \"user|imported|repo\"",
        "```",
        "",
        "### Rules",
        "- If key info is missing, write a placeholder and add an open_question.",
        "- If the user asks for external publishing/sharing, run `doc_redact` first.",
        "- If doc_type is software design, include architecture, data flow/DFD, interaction/sequence, and interfaces.",
        "- Preserve the order of numbered steps; do not merge multiple steps into a single line.",
        "(content removed)",
        "- For commands/options/modules lists, prefer Markdown tables with clear columns (e.g., Name | Purpose | Notes).",
        "- For database/schema content, output a Markdown table (Field | Type | Constraints) instead of raw SQL unless the user explicitly requests SQL.",
        "(content removed)",
        "(content removed)",
        "- For every figure/table, reference it in the surrounding paragraph (e.g., \"瑙佸浘 X\" / \"瑙佽〃 X\").",
        "- If figures/tables depend on missing data, mark values as \"TBD\" and add open_questions.",
        "- Use code blocks only for executable code or configuration snippets, not for tabular data.",
      ].join("\n"),
    },
    {
      name: "doc-review",
      description: "Review a doc for quality/compliance (blockers + fixes)",
      content: [
        "## Skill: doc-review",
        "",
        "Review a document for completeness, clarity, and basic compliance. Produce actionable fixes.",
        "",
        "### Inputs",
        "- The document content (Markdown/text; or use `doc_import` if it's binary)",
        "- Optional: standards (template requirements, style rules, redaction needs)",
        "",
        "### Output (required, YAML)",
        "```yml",
        "schema: doc.review.v1",
        "blockers: []",
        "warnings: []",
        "recommendations: []",
        "missing_info: []",
        "```",
        "",
        "### Checklist (answer each item)",
        "- [ ] No invented facts; unknowns are flagged",
        "- [ ] Required sections are present for the doc_type",
        "- [ ] Sensitive info risks called out; suggest `doc_redact` if needed",
        "- [ ] All figures/tables have captions and are referenced in nearby text",
        "- [ ] Each figure/table has 1鈥? sentences of explanation and (if applicable) data source/period",
        "- [ ] Numbered steps keep correct order; no inline list compression",
        "- [ ] Lists are proper Markdown lists (no inline dash separators)",
        "- [ ] Tabular data uses Markdown tables (not plain text or SQL)",
        "- [ ] Database/schema details are in tables unless SQL explicitly requested",
      ].join("\n"),
    },
    {
      name: "doc-diff-summary",
      description: "Summarize changes between two doc versions (structured)",
      content: [
        "## Skill: doc-diff-summary",
        "",
        "Summarize what changed between two versions of a document for reviewers.",
        "",
        "### Inputs",
        "- old_version text",
        "- new_version text",
        "",
        "### Output (required, YAML)",
        "```yml",
        "schema: doc.diff_summary.v1",
        "high_level: []",
        "notable_changes: []",
        "risks: []",
        "action_items: []",
        "```",
      ].join("\n"),
    },
    {
      name: "doc-translate",
      description: "Terminology-aware translation (with glossary)",
      content: [
        "## Skill: doc-translate",
        "",
        "Translate a document while keeping terminology consistent. Do not translate code identifiers.",
        "",
        "### Inputs",
        "- source_text",
        "- target_language",
        "- Optional: glossary/term rules",
        "",
        "### Output (required, YAML)",
        "```yml",
        "schema: doc.translate.v1",
        "target_language: \"\"",
        "glossary:",
        "  - src: \"\"",
        "    dst: \"\"",
        "translated_text: |",
        "  ...",
        "```",
      ].join("\n"),
    },
    {
      name: "doc-redaction-plan",
      description: "Plan redaction + external sharing risk checks",
      content: [
        "## Skill: doc-redaction-plan",
        "",
        "Create a concrete redaction plan for external sharing, including suggested `doc_redact` parameters.",
        "",
        "### Inputs",
        "- The document content (or `doc_import` output)",
        "- Sharing scope (who will see it), sensitivity level, required policies",
        "",
        "### Output (required, YAML)",
        "```yml",
        "schema: doc_redaction_plan.v1",
        "risk_summary: []",
        "redact_args:",
        "  kinds: [\"email\", \"phone\", \"cn_id\", \"bank_card\"]",
        "  strategy: \"mask\"",
        "additional_checks: []",
        "```",
        "",
        "### Rules",
        "- If the user requests external sharing/publishing, `doc_redact` must run first.",
        "- Redaction should be deterministic and auditable.",
      ].join("\n"),
    },
    {
      name: "doc-convert-pandoc",
      description: "Convert documents between formats using pandoc",
      content: [
        "## Skill: doc-convert-pandoc",
        "",
        "Convert documents between formats using pandoc.",
        "",
        "### Inputs",
        "- input file path",
        "- output file path (target extension)",
        "- Optional: pandoc format flags (from/to)",
        "",
        "### Steps",
        "1) Call `doc_convert` with inputPath/outputPath (and from/to if needed).",
        "2) If pandoc is missing, `doc_convert` will attempt a China mirror download and update PATH for this process.",
        "3) If auto-download fails, ask the user to install pandoc manually and provide URLs.",
        "",
        "### Manual install URLs",
        "- https://pandoc.org/installing.html",
        "- https://github.com/jgm/pandoc/releases/latest",
        "- https://mirrors.tuna.tsinghua.edu.cn/github-release/jgm/pandoc/LatestRelease/",
        "- https://mirrors.bfsu.edu.cn/github-release/jgm/pandoc/LatestRelease/",
        "",
        "### Rules",
        "- If pandoc is unavailable, do not attempt conversion.",
        "- Prefer explicit outputPath extensions to avoid ambiguity.",
      ].join("\n"),
    },
    {
      name: "novel-idea",
      description: "生成题材/设定草案（结构化 + 可写回）",
      content: [
        "## Skill：点子/设定生成（MVP）",
        "",
        "### 目标",
        "基于题材约束生成可落地的小说设定草案，并产出可写回 canon 的结构化条目草案。",
        "",
        "### 输入（契约）",
        "- 用户给出的题材/一句话梗概/关键禁忌/目标受众",
        "- 可选：现有 `novel/canon/*.yml`（若有，优先对齐而非重造同名设定）",
        "",
        "### 输出（契约）",
        "- 结构化产物（必需）：`schema: novel.idea.v1`（YAML）",
        "- 自然语言说明（可选）",
        "",
        "### 步骤",
        "1) 提炼题材约束（世界观类型、主冲突、情绪基调、禁用项）。",
        "2) 生成 1 个明确 premise + 3 条核心卖点。",
        "3) 给出最小可跑通 canon 草案：人物/势力/规则/事件/伏笔/术语（允许空数组）。",
        "4) 给出写作风险与降级建议（最多 5 条）。",
        "",
        "### 输出格式（YAML，必须）",
        "```yml",
        "schema: novel.idea.v1",
        "premise: \"一句话前提\"",
        "tone: [\"关键词1\", \"关键词2\"]",
        "taboo: [\"禁忌1\", \"禁忌2\"]",
        "selling_points:",
        "  - \"卖点1\"",
        "canon_drafts:",
        "  characters: []",
        "  factions: []",
        "  rules: []",
        "  timeline: []",
        "  foreshadow: []",
        "  glossary: []",
        "```",
        "",
        "### 自检清单（必须逐条回答）",
        "- [ ] 是否引入新设定/新人物？若是，是否在 `canon_drafts` 中给出条目草案？",
        "- [ ] 是否有任何内容违反 taboo？若有，已删除或替换？",
        "- [ ] 是否能在不新增模块的前提下写出第一章？若不能，列出最小补齐提问（≤3）？",
      ].join("\n"),
    },
    {
      name: "novel-plan",
      description: "生成章纲与场景卡（结构正确、可对账）",
      content: [
        "## Skill：大纲与节拍（MVP）",
        "",
        "### 目标",
        "为指定章节产出章纲与场景卡，明确目标/阻碍/转折/信息投放与伏笔 ID。",
        "",
        "### 输入（契约）",
        "- 目标章节 id（CH_*）",
        "- 现有 canon（人物/规则/时间线/伏笔/术语）",
        "- 可选：上一章摘要或上一次对账结论",
        "",
        "### 输出（契约）",
        "- 结构化产物（必需）：`schema: novel.plan.v1`（YAML）",
        "",
        "### 步骤",
        "1) 明确本章目标与结尾钩子（cliffhanger）。",
        "2) 拆成 3～7 个场景卡，保证“推进 + 信息投放 + 状态变化”至少各 1 次。",
        "3) 每个场景卡必须标注 refs（RULE_/FB_/CHAR_/ORG_/LOC_/ITEM_）。",
        "",
        "### 输出格式（YAML，必须）",
        "```yml",
        "schema: novel.plan.v1",
        "chapter_outline:",
        "  - chapter: CH_01_001",
        "    chapter_goal: \"本章要达成什么\"",
        "    turn: \"关键转折\"",
        "    cliffhanger: \"结尾钩子\"",
        "scene_cards:",
        "  - id: SC_CH_01_001_01",
        "    goal: \"场景目标\"",
        "    obstacle: \"主要阻碍\"",
        "    turn: \"场景转折\"",
        "    info_drop: [\"RULE_X\", \"FB_0001_X\"]",
        "    state_change:",
        "      - target: CHAR_X",
        "        set: { mood: \"...\" }",
        "```",
        "",
        "### 自检清单（必须逐条回答）",
        "- [ ] 是否每个场景都有明确 goal/obstacle/turn？",
        "- [ ] 是否至少投放 1 条 RULE_ 与 1 条 FB_（可复用已有）？",
        "- [ ] 是否存在“读者必需信息缺失”？若有，指出应在哪个场景补上。",
      ].join("\n"),
    },
    {
      name: "novel-draft",
      description: "按场景卡写正文（可读 + 可对账）",
      content: [
        "## Skill：写手（MVP）",
        "",
        "### 目标",
        "基于场景卡输出章节正文，保证可读性并尽量用 `[REF: ...]` 维护可追溯引用。",
        "",
        "### 输入（契约）",
        "- 目标章节 id（CH_*）",
        "- `outlines/<CH>.outline.md`（含场景卡）",
        "- canon（人物/规则/伏笔/时间线/术语）",
        "- 风格约束（禁用词/口吻/视角）",
        "",
        "### 输出（契约）",
        "- 结构化产物（必需）：`schema: novel.draft.v1`（YAML：frontmatter + refs_used）",
        "- 正文章节（Markdown）",
        "",
        "### 步骤",
        "1) 先生成 frontmatter（participants/locations/refs/status）。",
        "2) 按场景卡逐场景写，避免跳跃式总结。",
        "3) 在涉及设定/人物/伏笔处标注 `[REF: ...]`（逗号分隔）。",
        "",
        "### 输出格式（YAML + Markdown）",
        "```yml",
        "schema: novel.draft.v1",
        "frontmatter:",
        "  id: CH_01_001",
        "  title: \"章节名\"",
        "refs_used: [\"CHAR_X\", \"RULE_Y\"]",
        "```",
        "",
        "正文紧跟其后（不要包在代码块里）。",
        "",
        "### 自检清单（必须逐条回答）",
        "- [ ] 是否每个场景都对应一个 `## SC_...` 标题？",
        "- [ ] 是否引用了 canon 时都尽量给了 `[REF: ...]`？",
        "- [ ] 是否引入新设定？若是，列出需要写回的最小条目草案。",
      ].join("\n"),
    },
    {
      name: "novel-polish",
      description: "保守/重写两档润色（保持人设与世界观）",
      content: [
        "## Skill：润色与改写（MVP）",
        "",
        "### 目标",
        "输出保守润色与重写润色两版，并给出可执行修改摘要（为什么这样改）。",
        "",
        "### 输入（契约）",
        "- 原章节全文（含 frontmatter）",
        "- canon（人物口癖/禁用词/规则）",
        "- 用户偏好：更克制/更情绪/更快节奏等",
        "",
        "### 输出（契约）",
        "- 结构化产物（必需）：`schema: novel.polish.v1`（YAML：changes_summary）",
        "- 两版正文（Markdown）",
        "",
        "### 步骤",
        "1) 先做“保守润色”：删冗余、提画面、修语病、控节奏。",
        "2) 再做“重写润色”：允许重排段落，但不新增设定。",
        "3) 输出修改摘要：每版列 5 条以内“用户可验收”的变化点。",
        "",
        "### 自检清单（必须逐条回答）",
        "- [ ] 是否引入新设定/新人物？若是，标注并提供写回计划，否则删掉。",
        "- [ ] 是否破坏 POV/口吻一致性？若是已修正。",
        "- [ ] 是否存在说教式总结/网络梗？若有已移除。",
      ].join("\n"),
    },
    {
      name: "novel-summary",
      description: "章节摘要与卖点提炼（无剧透/含剧透）",
      content: [
        "## Skill：摘要与文案（MVP）",
        "",
        "### 目标",
        "为章节或全书输出无剧透/含剧透两版摘要，并提炼卖点 bullets。",
        "",
        "### 输入（契约）",
        "- 章节正文或章节列表",
        "- 可选：目标受众、平台风格",
        "",
        "### 输出（契约）",
        "- 结构化产物（必需）：`schema: novel.summary.v1`（YAML）",
        "",
        "### 输出格式（YAML，必须）",
        "```yml",
        "schema: novel.summary.v1",
        "no_spoiler: \"…\"",
        "with_spoiler: \"…\"",
        "selling_points:",
        "  - \"…\"",
        "```",
      ].join("\n"),
    },
    {
      name: "novel-continuity-check",
      description: "一致性对账（人物/时间线/设定/伏笔）并给最小修复方案",
      content: [
        "## Skill：Continuity / Canon 对账（MVP）",
        "",
        "### 目标",
        "发现设定冲突、时间线冲突、人物动机漂移、伏笔状态机问题，并输出最小可执行修复方案。",
        "",
        "### 输入（契约）",
        "- 目标章节正文（含 frontmatter 与 `[REF: ...]`）",
        "- canon（characters/rules/timeline/foreshadow）",
        "",
        "### 输出（契约）",
        "- 结构化产物（必需）：`schema: novel.check.v1`（YAML：issues + fixes）",
        "",
        "### 步骤",
        "1) 校验引用：所有 `[REF: ...]` 必须可在 canon 中找到。",
        "2) 校验时间线：同一时间锚点不处于互斥地点/状态。",
        "3) 校验人物：口癖/禁用词/动机是否明显冲突。",
        "4) 伏笔状态：planted → escalated → paid_off，不允许跳跃。",
        "5) 产出“最小修复方案”：改哪一句/补哪段/延期到哪章（必须可执行）。",
        "",
        "### 输出格式（YAML，必须）",
        "```yml",
        "schema: novel.check.v1",
        "issues:",
        "  - code: MISSING_REF",
        "    severity: error",
        "    message: \"引用不存在：RULE_X\"",
        "fixes:",
        "  - issue: MISSING_REF",
        "    minimal_change: \"在 canon/rules.yml 新增 RULE_X 条目草案；或删掉正文引用并改写该段。\"",
        "```",
      ].join("\n"),
    },
    {
      name: "novel-foreshadow",
      description: "伏笔/承诺追踪与回收对账（挖坑-升级-回收）",
      content: [
        "## Skill：伏笔与承诺回收检查（MVP）",
        "",
        "### 目标",
        "基于当前章节与 canon 的 foreshadow 表，输出未回收清单与补写点位。",
        "",
        "### 输入（契约）",
        "- 本章正文/大纲（可选）",
        "- canon/foreshadow.yml",
        "",
        "### 输出（契约）",
        "- 结构化产物（必需）：`schema: novel.foreshadow.v1`（YAML）",
        "",
        "### 输出格式（YAML，必须）",
        "```yml",
        "schema: novel.foreshadow.v1",
        "open_foreshadow: []",
        "unresolved: []",
        "suggested_actions:",
        "  - id: FB_0001_X",
        "    action: \"escalate\"",
        "    where: \"SC_CH_01_003_02\"",
        "```",
      ].join("\n"),
    },
    {
      name: "novel-flaw-finder",
      description: "缺点诊断（逻辑/节奏/动机/视角）并给可执行修复方案",
      content: [
        "## Skill：缺点诊断（MVP）",
        "",
        "### 目标",
        "找出章节在结构、逻辑、人物动机、节奏、视角、信息分配方面的问题，并给出最小可执行修复方案。",
        "",
        "### 输入（契约）",
        "- 章节正文或章节大纲",
        "- 可选：目标风格/读者预期",
        "",
        "### 输出（契约）",
        "- 结构化产物（必需）：`schema: novel.flaws.v1`（YAML）",
        "",
        "### 输出格式（YAML，必须）",
        "```yml",
        "schema: novel.flaws.v1",
        "issues:",
        "  - type: \"节奏\"",
        "    severity: \"high\"",
        "    evidence: \"指出具体段落/场景\"",
        "    fix: \"最小改动：删/并/改一句/补一段\"",
        "```",
      ].join("\n"),
    },
    {
      name: "novel-faction-relations",
      description: "势力/阵营关系与权力结构梳理（含 Mermaid）",
      content: [
        "## Skill：势力/阵营关系与权力结构（MVP）",
        "",
        "### 目标",
        "基于已知文本归纳势力清单、目标资源、盟友/敌对/附庸关系，并输出 Mermaid 关系图。",
        "",
        "### 输入（契约）",
        "- 章节正文/大纲/canon（至少其一）",
        "",
        "### 输出（契约）",
        "- 结构化产物（必需）：`schema: novel.factions.v1`（YAML）",
        "- Mermaid 图（必须）",
        "",
        "### 输出格式（YAML + Mermaid）",
        "```yml",
        "schema: novel.factions.v1",
        "factions: []",
        "edges: []",
        "questions: []",
        "```",
        "",
        "```mermaid",
        "graph TD",
        "  ORG_A -->|敌对| ORG_B",
        "```",
      ].join("\n"),
    },
    {
      name: "novel-character",
      description: "人物卡与动机/关系梳理（含口吻约束）",
      content: [
        "## Skill：人物卡与动机（MVP）",
        "",
        "### 目标",
        "基于现有文本/设定生成或校正人物卡，并产出可写回 canon 的条目草案与关系边。",
        "",
        "### 输入（契约）",
        "- 当前章节/大纲/设定（至少其一）",
        "- 可选：已有 canon/characters.yml",
        "",
        "### 输出（契约）",
        "- 结构化产物（必需）：`schema: novel.character.v1`（YAML）",
        "",
        "### 输出格式（YAML，必须）",
        "```yml",
        "schema: novel.character.v1",
        "characters: []",
        "relations: []",
        "voice_rules:",
        "  - id: CHAR_X",
        "    catchphrases: []",
        "    taboo: []",
        "```",
      ].join("\n"),
    },
  ] as const

  const builtinSkillContent = new Map<string, string>(BUILTIN_SKILLS.map((s) => [s.name, s.content]))

  export function getBuiltinContent(name: string) {
    return builtinSkillContent.get(name)
  }

  export const Info = z.object({
    name: z.string(),
    description: z.string(),
    location: z.string(),
  })
  export type Info = z.infer<typeof Info>

  export const InvalidError = NamedError.create(
    "SkillInvalidError",
    z.object({
      path: z.string(),
      message: z.string().optional(),
      issues: z.custom<z.core.$ZodIssue[]>().optional(),
    }),
  )

  export const NameMismatchError = NamedError.create(
    "SkillNameMismatchError",
    z.object({
      path: z.string(),
      expected: z.string(),
      actual: z.string(),
    }),
  )

  const OPENCODE_SKILL_GLOB = new Bun.Glob("{skill,skills}/**/SKILL.md")
  const CLAUDE_SKILL_GLOB = new Bun.Glob("skills/**/SKILL.md")

  export const state = Instance.state(async () => {
    const skills: Record<string, Info> = {}

    for (const skill of BUILTIN_SKILLS) {
      skills[skill.name] = {
        name: skill.name,
        description: skill.description,
        location: `builtin:${skill.name}`,
      }
    }

    const addSkill = async (match: string) => {
      const md = await ConfigMarkdown.parse(match).catch((err) => {
        const message = ConfigMarkdown.FrontmatterError.isInstance(err)
          ? err.data.message
          : `Failed to parse skill ${match}`
        Bus.publish(Session.Event.Error, { error: new NamedError.Unknown({ message }).toObject() })
        log.error("failed to load skill", { skill: match, err })
        return undefined
      })

      if (!md) return

      const parsed = Info.pick({ name: true, description: true }).safeParse(md.data)
      if (!parsed.success) return

      // Warn on duplicate skill names
      if (skills[parsed.data.name]) {
        log.warn("duplicate skill name", {
          name: parsed.data.name,
          existing: skills[parsed.data.name].location,
          duplicate: match,
        })
      }

      skills[parsed.data.name] = {
        name: parsed.data.name,
        description: parsed.data.description,
        location: match,
      }
    }

    // Scan .claude/skills/ directories (project-level)
    const claudeDirs = await Array.fromAsync(
      Filesystem.up({
        targets: [".claude"],
        start: Instance.directory,
        stop: Instance.worktree,
      }),
    )
    // Also include global ~/.claude/skills/
    const globalClaude = `${Global.Path.home}/.claude`
    if (await Filesystem.isDir(globalClaude)) {
      claudeDirs.push(globalClaude)
    }

    if (!Flag.OPENCODE_DISABLE_CLAUDE_CODE_SKILLS) {
      for (const dir of claudeDirs) {
        const matches = await Array.fromAsync(
          CLAUDE_SKILL_GLOB.scan({
            cwd: dir,
            absolute: true,
            onlyFiles: true,
            followSymlinks: true,
            dot: true,
          }),
        ).catch((error) => {
          log.error("failed .claude directory scan for skills", { dir, error })
          return []
        })

        for (const match of matches) {
          await addSkill(match)
        }
      }
    }

    // Scan .opencode/skill/ directories
    for (const dir of await Config.directories()) {
      for await (const match of OPENCODE_SKILL_GLOB.scan({
        cwd: dir,
        absolute: true,
        onlyFiles: true,
        followSymlinks: true,
      })) {
        await addSkill(match)
      }
    }

    return skills
  })

  export async function get(name: string) {
    return state().then((x) => x[name])
  }

  export async function all() {
    return state().then((x) => Object.values(x))
  }
}
